### ISSUE TITLE
crashes on 1.18.2 on server with other mods

### ISSUE THREAD

**Issue by youmukonpaku1337** [KenRouKoro/C3H6N6O6#2]
here's the crash log:
https://mclo.gs/JzjnFMF

**Comment by youmukonpaku1337** [comment]
I have disabled the entity and collection lithium mixins and removed servercore, this is a cyclonite issue

**Comment by KenRouKoro** [comment]
You do not have the pre-mod installed.

**Comment by KenRouKoro** [comment]
Here, and noted on modrinth.
https://modrinth.com/mod/koroworld-lib/

**Comment by youmukonpaku1337** [comment]
ah thanks

**Comment by youmukonpaku1337** [comment]
please mention that its required in description

**Comment by KenRouKoro** [comment]
Because of the license, KoroWorldLib Mod and C3H6N6O6 are not directly dependent, KoroWorldLib is providing the Class files for Hutool and JavaWebSocket to the ClassLoader of java.

**Comment by KenRouKoro** [comment]
I will add the module dependency requirements in the next release.

**Comment by youmukonpaku1337** [comment]
could you also mention that it's required in readme and modrinth's mod description?
