### ISSUE TITLE
Incompatibility with ServerCore leading to a crash

### ISSUE THREAD

**Issue by Aeldit** [KenRouKoro/C3H6N6O6#6]
The server crashes when using this mod and servercore
crash log : [pastebin link](https://pastebin.com/embed_js/VY1xryjr)
(see line 156)

**Comment by youmukonpaku1337** [comment]
oh damn i was about to report this, thanks

**Comment by KenRouKoro** [comment]
I see a code conflict between servercore and the C3H6N6O6 intercept entity tick, this is a principle level conflict and is not fixed by C3H6N6O6.
This issue should be reported to the author of servercore.

**Comment by youmukonpaku1337** [comment]
i just hope this'll be fixed on servercore's side because i use servercore for disabling spawn chunks completely and some other stuff

**Comment by youmukonpaku1337** [comment]
@Raphoulfifou please link the issue here after you make it on servercore's repo, i want to keep track of progress

**Comment by KenRouKoro** [comment]
The reason for the crash is that ServerCore is forcing the Mixin check to succeed, and this problem requires turning off ServerCore's Mixin check.

**Comment by youmukonpaku1337** [comment]
i guess you could make a PR on servercore for a toggle on the mixin check?

**Comment by KenRouKoro** [comment]
This is subject to the opinion of the ServerCore author.

**Comment by youmukonpaku1337** [comment]
i'll create the issue myself

**Comment by youmukonpaku1337** [comment]
done

**Comment by Aeldit** [comment]
ok so do I close this issue or do I just leave it like that ?

**Comment by youmukonpaku1337** [comment]
wait a bit

**Comment by youmukonpaku1337** [comment]
also, @KenRouKoro 
quote from that issue:
> As a sidenote for the author of cyclonite - I might've missed it but is there any reason as to why it tries to run non-passenger entity ticks async, but it doesn't do the same for passenger entity ticks? Just curious.

**Comment by KenRouKoro** [comment]
In fact cyclonite loads all Entity Tick asynchronously.

**Comment by youmukonpaku1337** [comment]
ah

**Comment by Wesley1808** [comment]
I'm not sure where it does that, I only looked at [ServerWorldMixin](https://github.com/KenRouKoro/C3H6N6O6/blob/master/src/main/java/cn/korostudio/c3h6n6o6/mixin/ServerWorldMixin.java#L63), for which it only seems to hook into `tickEntity()`, but not into `tickPassenger()`. Feel free to correct me if I'm wrong about this though.

**Comment by KenRouKoro** [comment]
I understand. The reason is this: there is no way to parallelize the method tickPassenger(), because the logic of the ride has to be sequential, unless I rewrite the whole ride system (which I obviously can't do).

**Comment by KenRouKoro** [comment]
The overhead of opening another thread to run it alone is theoretically greater than running it on the server thread, and given the actual gameplay, this method doesn't take up much computing weight (the entity that rides also has a separate tick, this method just handles the logic of riding alone)

**Comment by KenRouKoro** [comment]
However, it may be optimised later to run it after all entity ticks are in the queue.

**Comment by Wesley1808** [comment]
That overhead indeed probably isn't worth it. 

But if I'm not mistaken, `Entity#tickRiding()` does actually call `Entity#tick()`, not only riding logic. Meanwhile in the foreach loop on the entityList, before actually calling any tick logic it checks if the entity has a vehicle (is a passenger) - and if that vehicle is not removed and has the ticking entity as passenger (idk why it does a second check, probably some reason for that), it returns there.

Then again though, its only a small amount of entities so its probably not worth it.

**Comment by KenRouKoro** [comment]
Your description is probably an older version. The only specific tick that I can see in version 1.18.2 where I am is in tickPassenger(Entity vehicle, Entity passenger) is passenger.tickRiding().
The method tickPassenger() is called recursively.

**Comment by KenRouKoro** [comment]
There's also the fact that I've seen more than one pointless secondary check in Minecraft's code.
For example, when checking if a message sent by the player is a command, it checks twice if the string starts with a "/", which is really confusing.

**Comment by Wesley1808** [comment]
What I mean is that passenger.tickRiding() calls passenger.tick() itself. Not directly in the ServerWorld.tickPassenger() method itself.
My apologies for the few that commented on this ticket and are now (maybe) getting 12 emails though 😆

**Comment by KenRouKoro** [comment]
Oh, crap, I missed it.
But then again, it's better to leave the recursive call code to run on its own, after all, no one knows what will happen if it's intercepted, and MC has always been consistent in that regard.
——————————————————————————————————————————————————————
I think Github needs to start a private chat feature  lol

**Comment by himekifee** [comment]
Hook [this](https://github.com/himekifee/MCMTFabric/blob/55bb2116f8cda684baabcd7898b2c4781c25bc0d/src/main/java/net/himeki/mcmtfabric/mixin/ServerWorldMixin.java#L83). The old one was deprecated and caused minecart issues.
