### ISSUE TITLE
memoryleakfix incompatible with cyclonite

### ISSUE THREAD

**Issue by youmukonpaku1337** [KenRouKoro/C3H6N6O6#7]
cyclonite doesn't start with memoryleakfix, don't have the log but it can be reproduced easily

**Comment by KenRouKoro** [comment]
In my test environment it started successfully and with no exceptions, please provide your crash logs.
![image](https://user-images.githubusercontent.com/21196863/178043613-28771a9f-dcc1-4e15-aa30-c50977608d7c.png)

**Comment by youmukonpaku1337** [comment]
sure, i'll try a bit later

**Comment by youmukonpaku1337** [comment]
nvm doesn't seem to happen now
