### ISSUE TITLE
server crashes on player join and server motd is reset to default

### ISSUE THREAD

**Issue by youmukonpaku1337** [KenRouKoro/C3H6N6O6#8]
log: https://mclo.gs/SMdtL90
no idea what causes this

**Comment by youmukonpaku1337** [comment]
could it be because that player is using raknetify to connect?

**Comment by KenRouKoro** [comment]
You have two problems with this log, one is that the zombie entity is reporting errors (which it shouldn't). The other is a problem with ServerWorld.getOccupiedPointOfInterestDistance()
![image](https://user-images.githubusercontent.com/21196863/178057421-53898dec-182b-4388-b098-e97782b9bedb.png)

**Comment by youmukonpaku1337** [comment]
and how do i fix that?

**Comment by KenRouKoro** [comment]
Do you have any entity AI optimization mods installed?

**Comment by youmukonpaku1337** [comment]
don't think so

**Comment by youmukonpaku1337** [comment]
let me check

**Comment by youmukonpaku1337** [comment]
nope

**Comment by KenRouKoro** [comment]
This could also be caused by lithium, provided you have not turned off the two Mixin for lithium as described in the README.

**Comment by youmukonpaku1337** [comment]
i have disabled them

**Comment by youmukonpaku1337** [comment]
let me see, maybe it's debugify or memoryleakfix

**Comment by youmukonpaku1337** [comment]
it was

**Comment by youmukonpaku1337** [comment]
also is the low tps normal? it's at 17-18 for me

**Comment by youmukonpaku1337** [comment]
or is it supposed to be like that

**Comment by KenRouKoro** [comment]
No, most of your mspt is spent on System.err.

**Comment by youmukonpaku1337** [comment]
uhhh how could i stop that then

**Comment by youmukonpaku1337** [comment]
my tps is at 16-18 but the player says it doesn't feel very laggy

**Comment by youmukonpaku1337** [comment]
not sure now lol

**Comment by youmukonpaku1337** [comment]
oh now its at 8tps with a lot of entities and it is laggy

**Comment by youmukonpaku1337** [comment]
278 entities it seems

**Comment by youmukonpaku1337** [comment]
so uh cyclonite seems to make my server laggier

**Comment by KenRouKoro** [comment]
This is because most of the performance is taken up with printing error reports.

**Comment by youmukonpaku1337** [comment]
then how can i disable them?

**Comment by youmukonpaku1337** [comment]
they kill TPS

**Comment by KenRouKoro** [comment]
No, they are the last line of insurance to keep the server from crashing.

**Comment by KenRouKoro** [comment]
Conflict resolution is what counts.

**Comment by youmukonpaku1337** [comment]
well, here's the log https://mclo.gs/FgJDIV3

**Comment by youmukonpaku1337** [comment]
what are the conflicts

**Comment by KenRouKoro** [comment]
Wait a minute, your server isn't reporting any errors!

**Comment by KenRouKoro** [comment]
I suggest you use spark to print the performance stack.

**Comment by youmukonpaku1337** [comment]
which spark command should i use?

**Comment by youmukonpaku1337** [comment]
> Wait a minute, your server isn't reporting any errors!

that's why i was so confused

**Comment by KenRouKoro** [comment]
here ：https://spark.lucko.me/docs/Command-Usage
You need to run the /spark profiler command

**Comment by youmukonpaku1337** [comment]
sure

**Comment by youmukonpaku1337** [comment]
https://spark.lucko.me/DMwgkG4J36 spark report

**Comment by youmukonpaku1337** [comment]
log https://mclo.gs/XBmd0Jx

**Comment by youmukonpaku1337** [comment]
performance is abysmal

**Comment by KenRouKoro** [comment]
38.87% of the time is spent on processing packets, 16.42% on the block manager and 14.42% on MCFunc callbacks

**Comment by KenRouKoro** [comment]
38.87% of the time is spent on processing MCDataPack, 16.42% on the block manager and 14.42% on MCFunc callbacks

**Comment by youmukonpaku1337** [comment]
hmmm

**Comment by youmukonpaku1337** [comment]
no idea

**Comment by KenRouKoro** [comment]
I think it's a DataPack problem, which also occurs in MCMTCE with such blocks.

**Comment by KenRouKoro** [comment]
I think it's a DataPack problem, which has also occurred at MCMTCE.

**Comment by terminalmaid** [comment]
what could i do about this?

**Comment by youmukonpaku1337** [comment]
one second then, but the 2 most demanding datapacks i have are for worldgen, Terralith and Incendium

**Comment by youmukonpaku1337** [comment]
here's my datapack list:
 any-weather-channeling-e951  silk-touch-spawners-v2-2  yumis_essentials_v2
craftable_end_portal_frame   terralith
incendium                    villager-lead-e3400

**Comment by youmukonpaku1337** [comment]
(yumis essentials is an old datapack i made for some recipes)

**Comment by KenRouKoro** [comment]
I have tested the DataPack Paradise on MCMTCE and had the same problem, the packet processing time took up 80% of the total processing time.

**Comment by youmukonpaku1337** [comment]
hmmm, so which one of my datapacks might cause this?

**Comment by KenRouKoro** [comment]
Related to biological entities.

**Comment by KenRouKoro** [comment]
There is also the fact that Terralith is not very compatible with C2ME.

**Comment by youmukonpaku1337** [comment]
it is, i used it for like a month with it at this point, it makes worldgen 2x slower but is worth it

**Comment by KenRouKoro** [comment]
Under C2ME, the rate of terrain generation in Terralith's "Grand Canyon of Errors" has skyrocketed.

**Comment by youmukonpaku1337** [comment]
> Related to biological entities.

soo it could be incendium, villagerleads or anyweatherchanneling

**Comment by youmukonpaku1337** [comment]
> Under C2ME, the rate of terrain generation in Terralith's "Grand Canyon of Errors" has skyrocketed.

what?

**Comment by KenRouKoro** [comment]
> 

A type of terrain break caused by a generator error.

**Comment by youmukonpaku1337** [comment]
well i don't know but terralith never caused any issues for me with c2me

**Comment by youmukonpaku1337** [comment]
so it's another datapack

**Comment by KenRouKoro** [comment]
To be honest, MCVanilla's DataPack processor is a mess.

**Comment by youmukonpaku1337** [comment]
rewrite it then /j

**Comment by KenRouKoro** [comment]
> well i don't know but terralith never caused any issues for me with c2me

It actually causes a significant performance drain as well as terrain errors, but does not lead to crashes and error reporting.

**Comment by youmukonpaku1337** [comment]
yeah i know that generation performance is 2x slower

**Comment by KenRouKoro** [comment]
I can't understand why MJ would use JSON as a DataPack language, it's not what JSON is supposed to do, JSON is just a data markup language.

**Comment by youmukonpaku1337** [comment]
good question

**Comment by youmukonpaku1337** [comment]
no idea

**Comment by youmukonpaku1337** [comment]
but, you got any idea which datapack could cause the TPS drain?

**Comment by KenRouKoro** [comment]
To be honest, I don't know. I usually write my own mods or write kubejs for this type of functionality to solve it.

**Comment by youmukonpaku1337** [comment]
oh

**Comment by KenRouKoro** [comment]
I don't know anything about DataPack.

**Comment by youmukonpaku1337** [comment]
wait, the shenandoahGC cycles seem extremely long

**Comment by youmukonpaku1337** [comment]
hmmmmm

**Comment by KenRouKoro** [comment]
The MCDataPack run generates a large number of objects.

**Comment by youmukonpaku1337** [comment]
hmmmmmm

**Comment by youmukonpaku1337** [comment]
sounds a lot like incendium

**Comment by youmukonpaku1337** [comment]
could you try using incendium on your test server?

**Comment by KenRouKoro** [comment]
What is it for, just asking.

**Comment by youmukonpaku1337** [comment]
amazing nether terrain and new bosses and items in nether

**Comment by youmukonpaku1337** [comment]
made by the creators of terralith

**Comment by youmukonpaku1337** [comment]
it adds new mobs too i think

**Comment by youmukonpaku1337** [comment]
but yeah test it

**Comment by youmukonpaku1337** [comment]
okay it still brings tps down to 5 even with no mods, even causes a watchdog crash

**Comment by KenRouKoro** [comment]
Puzzling.

**Comment by youmukonpaku1337** [comment]
*no datapacks

**Comment by youmukonpaku1337** [comment]
but yeah, it's weird

**Comment by youmukonpaku1337** [comment]
i'll fire up a test server later

**Comment by youmukonpaku1337** [comment]
btw @KenRouKoro did you make the client logic code?

**Comment by KenRouKoro** [comment]
It doesn't work yet and I'm still fixing why BlockEntity isn't being run correctly in single player.

**Comment by youmukonpaku1337** [comment]
okay

**Comment by KenRouKoro** [comment]
The new version already supports single player.
